apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-service
  template:
    metadata:
      labels:
        app: credit-service
        version: v1
    spec:
      containers:
        - name: credit-service
          image: sainturb/credit-service:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: credit-config
          securityContext:
            runAsUser: 1000