apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        version: v1
    spec:
      containers:
        - name: order-service
          image: sainturb/order-service:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: order-config
          securityContext:
            runAsUser: 1000