apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  labels:
    app: product-service
data:
  KAFKA_SERVERS: kafka-0.kafka-headless.default.svc.cluster.local:9092,kafka-1.kafka-headless.default.svc.cluster.local:9092
  ELASTIC_URIS: elasticsearch-master.default.svc.cluster.local:9200
  SPRING_DATASOURCE_URL: jdbc:postgresql://product-database:5432/postgres
  ACCOUNT_SERVICE: http://account-service:8081
