apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        version: v1
    spec:
      containers:
        - name: product-service
          image: sainturb/product-service:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: product-config
          securityContext:
            runAsUser: 1000