apiVersion: v1
kind: Service
metadata:
  name: product-service # Sets service name
  labels:
    app: product-service # Labels and Selectors
    version: v1
spec:
  type: NodePort # Sets service type
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
  selector:
    app: product-service