apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        version: v1
    spec:
      containers:
        - name: payment-service
          image: sainturb/payment-service:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: payment-config
          securityContext:
            runAsUser: 1000