### Batch start process
PUT http://localhost:8082/api/batch/start
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImFkbWluQG1pdS5lZHUiLCJmdWxsbmFtZSI6ImFkbWluIGFkbWluIiwiaWQiOjIsInJvbGVzIjpbIkFETUlOIl0sInVzZXJuYW1lIjoiYWRtaW4ifQ.smvisH5PDc1TcyYBwUutfDBlg44PpEGzKDshFa0xpJmZnLljheB2yBkbfGCsRYp_BMWejOVccmPcOcKAPXQkRg

### Batch start process
PUT http://localhost:8082/api/bulk
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImFkbWluQG1pdS5lZHUiLCJmdWxsbmFtZSI6ImFkbWluIGFkbWluIiwiaWQiOjIsInJvbGVzIjpbIkFETUlOIl0sInVzZXJuYW1lIjoiYWRtaW4ifQ.smvisH5PDc1TcyYBwUutfDBlg44PpEGzKDshFa0xpJmZnLljheB2yBkbfGCsRYp_BMWejOVccmPcOcKAPXQkRg

### Search products
GET localhost:9200/product/_search
Content-Type: application/json

{
  "query": {
    "query_string": {
      "query": "homeType: apartment & totalOccupancy: 4"
    }
  }
}

### Search products
GET localhost:9200/product/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "homeType": "apartment"
          }
        },
        {
          "term": {
            "totalOccupancy": 4
          }
        },
        {
          "term": {
            "hasInternet": true
          }
        },
        {
          "term": {
            "hasAirCon": true
          }
        },
        {
          "range": {
            "availableUntil": {
              "lte": "2022-10-01"
            }
          }
        },
        {
          "range": {
            "availableFrom": {
              "gte": "2022-09-19"
            }
          }
        }
      ]
    }
  },
  "size": 10
}



### Search products 1
http://localhost:8082/api/_search?homeType=apartment&totalBedrooms=3,5&availableFrom=2022-09-22&availableUntil=2022-10-02&hasTV=0&page=0&size=10
Content-Type: application/json

###
DELETE http://localhost:9200/_all

### Create review
POST localhost:8082/api/reviews/create/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImFkbWluQG1pdS5lZHUiLCJmdWxsbmFtZSI6ImFkbWluIGFkbWluIiwiaWQiOjIsInJvbGVzIjpbIkFETUlOIl0sInVzZXJuYW1lIjoiYWRtaW4ifQ.smvisH5PDc1TcyYBwUutfDBlg44PpEGzKDshFa0xpJmZnLljheB2yBkbfGCsRYp_BMWejOVccmPcOcKAPXQkRg
Content-Type: application/json

{
  "message": "Message",
  "rating": 1
}

### Create review
GET localhost:8082/api/products/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImFkbWluQG1pdS5lZHUiLCJmdWxsbmFtZSI6ImFkbWluIGFkbWluIiwiaWQiOjIsInJvbGVzIjpbIkFETUlOIl0sInVzZXJuYW1lIjoiYWRtaW4ifQ.smvisH5PDc1TcyYBwUutfDBlg44PpEGzKDshFa0xpJmZnLljheB2yBkbfGCsRYp_BMWejOVccmPcOcKAPXQkRg
Content-Type: application/json

### Search products
GET localhost:9200/product/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "id": "1"
          }
        }
      ]
    }
  }
}

### Batch start process
PUT http://localhost:8082/api/products/1/availability
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImFkbWluQG1pdS5lZHUiLCJmdWxsbmFtZSI6ImFkbWluIGFkbWluIiwiaWQiOjIsInJvbGVzIjpbIkFETUlOIl0sInVzZXJuYW1lIjoiYWRtaW4ifQ.smvisH5PDc1TcyYBwUutfDBlg44PpEGzKDshFa0xpJmZnLljheB2yBkbfGCsRYp_BMWejOVccmPcOcKAPXQkRg
