version: '3.0'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=elastic-cluster
      - ELASTIC_PASSWORD=elastic
    ports:
      - 9200:9200
      - 9300:9300
  product-db:
    image: postgres
    container_name: product-db
    restart: always
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres