apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
  labels:
    app: account-service
data:
  REDIS_HOST: redis-master.default.svc.cluster.local
  SPRING_DATASOURCE_URL: jdbc:postgresql://account-database:5432/postgres
