apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        version: v1
    spec:
      containers:
        - name: notification-service
          image: sainturb/notification-service:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: notification-config
          securityContext:
            runAsUser: 1000