apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  labels:
    app: notification-service
data:
  KAFKA_SERVERS: kafka-0.kafka-headless.default.svc.cluster.local:9092,kafka-1.kafka-headless.default.svc.cluster.local:9092