apiVersion: v1
kind: Service
metadata:
  name: notification-service # Sets service name
  labels:
    app: notification-service # Labels and Selectors
    version: v1
spec:
  type: ClusterIP # Sets service type
  ports:
    - name: http
      protocol: TCP
      port: 8089
      targetPort: 8089
  selector:
    app: notification-service